version: '4.32'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: barterly
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root123
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
