FROM maven:3.9.5-amazoncorretto-21-debian-bookworm
ENV TZ="Asia/Tashkent"
RUN mkdir /app
COPY . /app/
WORKDIR /app
RUN cd /app/
RUN cp -f /app/src/main/resources/application-dev.yml /app/src/main/resources/application.yml
RUN mvn clean package -DskipTests
RUN mvn install  -DskipTests
RUN cp -f /app/target/*.jar /app/application.jar
WORKDIR /app
ENTRYPOINT ["java", "-jar", "application.jar"]
