version: "3.5"
services:
  db:
    container_name: ${CONTAINER_NAME}-postgres
    image: postgres:12
    volumes:
      - './postgres/data:/var/lib/postgresql/data'
      - './postgres:/var/lib/postgresql'
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root123
    ports:
      - target: 5432
        published: 5483
        protocol: tcp
        mode: host
  app:
    image: ${CONTAINER_NAME}-app:${APP_VERSION}.${BUILD_NUMBER}
    container_name: ${CONTAINER_NAME}-app
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: .env
    restart: always
    ports:
      - target: 8080
        published: ${DOMAIN_PORT}
        protocol: tcp
        mode: host
